### ISSUE TITLE
pre-commit hook removes files from the commit

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#28] opened 2023-11-21 09:54 UTC
**Describe the bug**

With latest version, if I run `pre-commit run -a`, it will pass OK. However, if I run `git commit`, it will remove `.ctt` dir automatically from the commit.

**To Reproduce**

1. Uncompress [repo.zip](https://github.com/KyleKing/copier-template-tester/files/13424543/repo.zip)
2. Clone it (it's a bundled repo) with `git clone ./sample there && cd there`
3. `pre-commit install`
4. Change anything: `touch foo && git add foo`
5. Check `git status`; all is OK, just as expected.
6. Commit the change: `git commit -m testing`. It will do something like:

        ➤ git commit -m testing
        copier-template-tester...................................................Passed
        [main da038e0] testing
         1 file changed, 0 insertions(+), 0 deletions(-)
         create mode 100644 foo

   That's wrong. 

7. Check with `git status` that `.ctt` was created but is untracked:

        ➤ git status
        On branch main
        Untracked files:
          (use "git add <file>..." to include in what will be committed)
	        .ctt/
        
        nothing added to commit but untracked files present (use "git add" to track)

8. OK, let's add `.ctt` and commit it:

        ➤ git add .ctt

        ➤ git commit -m add-ctt
        copier-template-tester...................................................Failed
        - hook id: copier-template-tester
        - exit code: 1
        
        Starting Copier Template Tester for /tmp/tmp.4ZCnGezWFN
        Note: If files were modified, pre-commit will report a failure.
        
        Using `copier` to create: .ctt/defaults
        Traceback (most recent call last):
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/bin/ctt", line 8, in <module>
            sys.exit(run_cli())
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier_template_tester/main.py", line 67, in run_cli
            run(base_dir=args.base_dir, check_untracked=args.check_untracked)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier_template_tester/main.py", line 44, in run
            write_output(src_path=input_path, dst_path=base_dir / output_path, data=defaults | data)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier_template_tester/_write_output.py", line 146, in write_output
            copier.run_copy(str(src_path), dst_path, **kwargs)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/main.py", line 980, in run_copy
            with Worker(src_path=src_path, dst_path=Path(dst_path), **kwargs) as worker:
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/main.py", line 205, in __exit__
            raise value
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/main.py", line 981, in run_copy
            worker.run_copy()
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/main.py", line 736, in run_copy
            self._print_message(self.template.message_before_copy)
          File "/nix/store/c3cjxhn73xa5s8fm79w95d0879bijp04-python3-3.10.13/lib/python3.10/functools.py", line 981, in __get__
            val = self.func(instance)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/template.py", line 325, in message_before_copy
            return self.config_data.get("message_before_copy", "")
          File "/nix/store/c3cjxhn73xa5s8fm79w95d0879bijp04-python3-3.10.13/lib/python3.10/functools.py", line 981, in __get__
            val = self.func(instance)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/template.py", line 272, in config_data
            result = filter_config(self._raw_config)[0]
          File "/nix/store/c3cjxhn73xa5s8fm79w95d0879bijp04-python3-3.10.13/lib/python3.10/functools.py", line 981, in __get__
            val = self.func(instance)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/template.py", line 231, in _raw_config
            for p in self.local_abspath.glob("copier.*")
          File "/nix/store/c3cjxhn73xa5s8fm79w95d0879bijp04-python3-3.10.13/lib/python3.10/functools.py", line 981, in __get__
            val = self.func(instance)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/template.py", line 478, in local_abspath
            result = Path(clone(self.url_expanded, self.ref))
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/copier/vcs.py", line 190, in clone
            git(
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/plumbum/commands/base.py", line 113, in __call__
            return self.run(args, **kwargs)[1]
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/plumbum/commands/base.py", line 252, in run
            return p.run()
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/plumbum/commands/base.py", line 215, in runner
            return run_proc(p, retcode, timeout)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/plumbum/commands/processes.py", line 299, in run_proc
            return _check_process(proc, retcode, timeout, stdout, stderr)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/plumbum/commands/processes.py", line 17, in _check_process
            proc.verify(retcode, timeout, stdout, stderr)
          File "/var/home/yajo/.cache/pre-commit/repoozco1e_t/py_env-python3.10/lib/python3.10/site-packages/plumbum/machines/base.py", line 27, in verify
            raise ProcessExecutionError(
        plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
        Command line: | /usr/libexec/git-core/git --git-dir=.git --work-tree=/tmp/tmp.4ZCnGezWFN commit -m 'Copier automated commit for draft changes' --no-verify --no-gpg-sign
        Stdout:       | On branch main
                      | Your branch is up to date with 'origin/main'.
                      | 
                      | nothing to commit, working tree clean
        
9. Nothing to commit? What's happening?

        ➤ git status
        On branch main
        nothing to commit, working tree clean
    
    ![](https://media.giphy.com/media/yjs4noW0nqYc8/giphy.gif)

**Expected behavior**

When ctt produces changes, it should fail (problem at step 6).

When ctt changes are added to commit, they should be kept (step 8).

**Comment by KyleKing** [comment] 2023-11-21 13:20
Thanks for the source code! I can replicate the same issue 😞 

On an initial pass:

1. It looks like the logic for detecting a dirty repository and making a commit is somehow conflicting with copier|ctt|pre-commit|?: https://github.com/copier-org/copier/commit/6cc94c6ad12d7e858a50f3ba7fee0afb77b2fd6c
2. I found a separate issue with recursion when the `.ctt` directory wasn't ignored (I'm not sure why that isn't a problem here)

I'll keep investigating and see if I can figure out what is going on

**Comment by KyleKing** [comment] 2023-11-21 14:29
Okay, so I might have a patch released in `2.1.0`

There are a couple of things still to address, but in testing locally, the `plumbum` error wasn't occurring. The root cause seems to have been part of a change intended to resolve #24 by removing the `.ctt` destination directory that caused a regression for this issue (https://github.com/KyleKing/copier-template-tester/commit/8e9aa2e96fd505e242d6900f78212f756c6f41ae)

Remaining Issues:

1. [ ] Exclude rules should be added dynamically when no `subdir` is specified. The current approach to detect recursion only happens in a test environment and requires the user to take manual steps (which could be handled within `ctt`)
2. [ ] Restore removal of `dst_dir` to support non-updatable templates (#24), but in a way that doesn't conflict with the internal logic of copier
3. [ ] When `.ctt` is first created and untracked, raise an error that it needs to be committed (pre-commit returns success currently)

**Comment by KyleKing** [comment] 2023-11-23 12:44
I released `2.1.1` to address the three tasks from above and tested it against the sample repo.

Let me know if this resolved the issues!

**Closed by KyleKing** 2023-11-23 12:44 UTC
Labels: Type: Bug

**Comment by yajo** [comment] 2023-11-27 09:51
Thanks! It seems to work now ❤️
